# 服务器配置
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 3600
    encoding:
      charset: UTF-8
      force: true
    context-path: /api
# spring配置
spring:
  application:
    name: EmploymentAnalysis
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/employee?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=UTF8&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true&cachePrepStmts=true&allowMultiQueries=true&serverTimeZone=Asia/Shanghai&sslMode=DISABLED
    username: root
    password: woshidale123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.xll.employmentanalysis.dto, cn.xll.employmentanalysis.vo
  lazy-loading-enabled: true
  aggressive-lazy-loading: false
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  helperDialect: mysql # 指定数据库，不指定的话会默认自动检测数据库类型
  # 是否启用分页合理化。
  # 如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；
  #  不启用的，以上两种情况都会返回空数据
  reasonable: true
  # 是否开启自动分页? 分页插件会从查询方法的参数值中，自动 params 配置的字段中取值，查找到合适的值时就会自动分页。
  supportMethodsArguments: false # 默认值false，
  #  用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，
  #  不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;
  #  reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count=countSql

# ajax跨域参
cors:
  response:
    header:
      # 允许跨域访问资源的访问者的url 注意：若参数值为*时 accessControlAllowCredentials 参数必须为false
      accessControlAllowOrigin: "Origin"
      # requestMethod
      accessControlAllowMethods: "POST, GET, PUT, PATCH, OPTIONS, DELETE"
      # 预检请求间隔
      # 0 表示每次异步请求都发起预检请求，也就是说，发送两次请求。
      # 3600 表示隔60分钟才发起预检请求。也就是说，发送两次请求
      accessControlAllowMaxAge: "3600"
      # 接受的 requestHeader包含
      accessControlAllowHeaders: "Origin, Accept, x-auth-token,Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization, Code-Token, Access-Token, uId, oId"
      # 客户端是否携带cookie
      # false 为不允许
      # true 为运行 注意：若参数值true时 accessControlAllowOrigin的参数值不能为* 必须指定允许跨域访问资源的访问者的url
      accessControlAllowCredentials: "true"


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.xll.employmentanalysis.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn



